#=============================================================================
[[layers]]

  name = 'autocomplete', auto_completion_return_key_behavior = "complete", auto_completion_tab_key_behavior = "smart" },
  name = 'shell', default_position = 'top', default_height = 30 },
  name = 'git' },
  name = 'VersionControl' },
  name = "lang#python", python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    '',
  ], 
  enable_typeinfo = true, 
  format_on_save = true, 
  python_interpreter = '/usr/bin/python', 
  enabled_linters = [
    'pylint',
  ] 
 name = 'lsp', enabled_clients = [
    'pyright',
  ],
  name = "lang#sh", 
  bash_file_head = [
    '#!/usr/bin/env bash',
    '#=============================================================================',
    '# filename.toml --- bash script',
    '# Copyright (c) 2016-2021 @EasyQuest',
    '# Author: Ivan Yastrebov < easy-quest@mail.ru >',
    '# URL: https://easy-quest.github.io/web/',
    '# License: GPLv3',
    '#=============================================================================',
    '',
    '',
    '',
  ] 
   name = "format"
   name = "lang#red"
   name = "lang#toml" 
   name = "sudo" 
   name = "lang#autohotkey" 
   name = "lang#autoit" 
   name = 'lang#coffeescript' 
   name = 'lang#d'
   name = 'go'
   name = "lang#lua"

# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "blue"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Включить автозаполненный слой

  
  
  


  
  
  


  

  


  
  
  
  
  
  


  
  


  
  


  


  
  


  


  


  


  


  

[layers]
  name = "lang#e"


  


  


  

